### ISSUE TITLE
Add swipe left and right to the top tab view

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#174]
Otherwise it is inconvenient to use on the big screen

**Comment by DmitryBespalov** [comment]
Do we need it? @MouazAlzahabi @tschubotz

**Comment by tschubotz** [comment]
> Do we need it? @MouazAlzahabi @tschubotz

Sorry, I'm missing context here. What is this ticket about?

**Comment by DmitryBespalov** [comment]
It is an idea to use "swipe left" and "swipe right" gesture to switch between Balances and Collectibles in the Assets screen, or between Safe Settings and App Settings on the Settings screen, or between Queued and History in the Transactions screen

**Comment by tschubotz** [comment]
ah, ok, thanks for explaining. That's a "nice to have" for me currently and not a "must have"

**Comment by elgatovital** [comment]
not needed
