### ISSUE TITLE
[iOS] Transactions List

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-ios#175]
- [ ] Create API endpoint in SafeTransactionService.swift
- [ ] Define ConfirmationType enum: will be used in parse Confirmation object.
- [ ] Define signatureType enum: will be used in parse Confirmation object.
- [ ] Create Transaction struct
- [ ] Create Confirmation struct: Example
```
{
"owner":"0x19433c47bF16f0D6E14Ff68ec4f5fafA2d9C8756",
"submissionDate":"2020-05-23T01:18:17.546177Z",
"transactionHash":"0xab11e8142725d5b82e97dde31d10870b8c362b875e73d287fece35eae2265448",
"confirmationType":"CONFIRMATION",
"signature":"0x00000000000000000000000019433c47bf16f0d6e14ff68ec4f5fafa2d9c8756000000000000000000000000000000000000000000000000000000000000000001",
"signatureType":"APPROVED_HASH"
}
```

- [ ] Define TransferType enum: will be used in parse Transfer object.
- [ ] Create Transfers struct: Example: 
```
{
"type":"ERC20_TRANSFER",
"executionDate":"2020-05-23T04:14:22Z",
"blockNumber":6536788,
"transactionHash":"0x979fc193baa01cecd58e229121c45b0187e6217d0e097b1333ecdfad27e2be5f",
"to":"0x6f965E48347AF3Df65c14CCc176A9CbeCEa0eDb5",
"value":"15151200",
"tokenId":null,
"tokenAddress":"0x0014F450B8Ae7708593F4A46F8fa6E5D50620F96",
"from":"0x441E604Ad49602c0B9C0B08D0781eCF96740786a"
}
```

- [ ] Define TXType enum: used in Transaction object.
- [ ] Empty list state 
- [ ] Create transactions list with the following criteria: 
- User sees 2 sections:
  - A section for txs waiting for confirmations
  - Another section for txs that have been executed or cancelled
- User sees all txs sorted in both sections:
  - Waiting for confirmations
    - Sorted by nonce, **ascending**
    - If 2 txs with same nonce, then put the one with the later creation date higher
  - Executed and cancelled
    - Executed txs sorted by execution date, **descending** (Both incoming and outgoing)
    - Add cancelled txs in that list with their created timestamp
  - Find more on the sorting [in this doc](https://docs.google.com/document/d/1bXp38-roy5kJhJWcADCYo4b5ZZ92aB61uny9e6U45gc/edit).
- User sees all incoming and outgoing transactions.
- User can explore transaction details further by tapping on a transaction.
- Transactions should be identifed by their nonce. There should **not** be another identifier.

- [ ] Create TransactionCell: Should display:
    - Date
    - Status 
    - Confirmation count: only if in Queue section 
    - Identicon: if transaction has to address 
    - to address: if available 
    - Data length: if available 
    - Transaction type icon
    - Value and currency

Screenshot: 
[zpl.io/VOGMB4Q](url)

**Comment by DmitryBespalov** [comment]
Information:
- [ ] Missing link to the transaction service endpoint (safes/{address}/all-transactions)
- [ ] List of all types of transactions
- [ ] List of all transaction states


Suggestions for splitting this ticket:
- [ ] Extract "empty list" into a new ticket
- [ ] Extract the "transaction cell" UI into new ticket
- [ ] Extract the "transaction list UI" (the table of transactions) in a separate ticket
- [ ] Extract the networking and parsing into new ticket
