### ISSUE TITLE
[iOS] Transaction Details Type and Status

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-ios#177]
### Type and Status UI Map

![TransactionTypeAndStatusUIMap](https://user-images.githubusercontent.com/284056/84517218-80081b00-acbe-11ea-8338-6b7b89642b46.png)

**Comment by DmitryBespalov** [comment]
- [ ] Extract the "confirmations view" into a new ticket
- [ ] Extract the header views into a new ticket
- [ ] Extract all other fields into a new ticket
- [ ] Keep this ticket only for the whole transaction details screen

**Comment by liliya-soroka** [comment]
Verified 0.5.0 (62)
