### ISSUE TITLE
[iOS] Push Notifications

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios#178]
Dependency:
- Configuration management (we need to store secret files)
- For now, we can add them to .gitignore, or we can use a similar encrypted files approach as we did in the legacy app

Setup: https://firebase.google.com/docs/ios/setup
Pods that we need:
- pod 'Firebase/Analytics'
- pod 'Firebase/Messaging'
- pod 'Firebase/Crashlytics'
- pod 'Firebase/Performance'

iOS
- register on push notifications — safe address; push token; client; buildNumber; version number; bundle (see new service implementation and the legacy app) — send on receiving a new token from Firebase (MessagingDelegate) — send on every app start
- unregister when deleting a safe
- Add remoteNotificationsHandler extension (check the legacy app) — need to clarify with Uxio what localization keys are we going to use

**Comment by DmitryBespalov** [comment]
This is a duplicate ticket, should be closed
