### ISSUE TITLE
[iOS] Crashlytics

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios#179]
Dependency: Push Notifications #178

Enable Crashlytics logger.
- Uncomment lines in CrashlyticsLogger
- Enable logger in LogService
- Enable tests in CrashlyticsLoggerTests & LogServiceTests
- Add loggers to the configuration
- Setup loggers on app start
- Test that it works

**Comment by liliya-soroka** [comment]
@sche , the option Crash the App appears in the App settings->Advanced.
Is it for Crashlitics testing?
Note: There is no record in the https://console.firebase.google.com/u/2/project/safe-firebase-staging/crashlytics/app/ios:io.gnosis.multisig.staging.rinkeby/issues?state=open&time=1594771200000:1594943999000&type=crash when I am using the Crash the app option

**Comment by liliya-soroka** [comment]
Verified:
The event for App settings->Advanced -> crash app is tracked
But the fatal errors are not tracked - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/398
 app version 0.7.0 (93)
