### ISSUE TITLE
[iOS] Pull to refresh

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios#180]
Pull to refresh functionality on screens with networking

- Balances
- Safe Settings
- Transactions
~~Collectibles~~

https://gnosisinc.slack.com/archives/GRN088HEG/p1592820149001000

**Comment by liliya-soroka** [comment]
Pull to refresh was not added to the Collectibles page.
Please, add the mark if it's out of scope for the task

app version 0.6.0(73)

**Comment by sche** [comment]
fixed the issue description

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0(73)
