### ISSUE TITLE
[iOS] Collectibles list screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#183]
Screen UI https://zpl.io/bA1pdle

sections with cards  that have image, name, and short description. Section has icon and name. 

Each section is the name of the contract.  Open question: where do we get icon of the  token itself?

Screen with loading indicator and showing error message in case of loading fails.

### Tracking 
Screen tracking `assets_collectibles`

**Comment by liliya-soroka** [comment]
The task is done according the description in the epic.
But there is the issue with displaying the basic information 
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/370
