### ISSUE TITLE
[iOS] Collectible Detail Screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#184]
Looks like a List with image, texts, contract cell, and etherscan link.

https://zpl.io/bLlzvM7

https://zpl.io/VkRq4jK

https://zpl.io/a8oMdNx

### Screen tracking
`assets_collectibles_details`

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (93)
The task is done according to the description in the epic.
But there is the issue with displaying the basic information
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/370
