### ISSUE TITLE
[iOS] Transaction details: other fields

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-ios#186]
Transaction details screen should display the following:

- [x] Data section: if available, should be expandable
- [x] Execute date
- [x] Create date
- [x] Advanced: link to view advanced tx details
- [x] View on Etherscan

![OtherTxDetailsFields](https://user-images.githubusercontent.com/284056/84517317-a6c65180-acbe-11ea-90d5-40b57adadf18.png)

### Screenshot:
[https://zpl.io/2GJA7RJ](url)

**Comment by liliya-soroka** [comment]
contains trivial UI issue - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/283

Verified
app version 0.5.0 (62)
