### ISSUE TITLE
[iOS] Transaction details Confirmations View

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-ios#187]
A view to display confirmation/rejection status for each owner

[https://zpl.io/ag4pqNZ](url)
[https://zpl.io/VDJwk4w](url)
[https://zpl.io/bPJ7zv6](url)

### Confirmations, rejections & executions
- Sorted by time, ascending.
- [iOS](https://zpl.io/ag4pqNZ), [Android](https://zpl.io/VKZvYdA)
- Figuring out rejections and cancel transactions is quite tedious. Rejections of 1 transaction are technically confirmations of a "cancel" transaction 🤯. Hence we decided to not show rejections, yet, just confirmations. On the transaction list we show all transactions, i.e. including the "0 ETH, no data" txs (which are "cancel" transactions). We take the following simplifications:

##### Tx executed (successful or failed)

- Confirmations list includes the following:
  - Created
  - Confirmed (once for every owner that confirmed)
  - Executed/failed (Incl. executor address)

##### Tx not executed, but there is another executed transaction with the same or higher nonce.

- That means this txs was implicitly cancelled since its nonce has been "consumed" by the executed tx.
- Confirmations list includes the following:
  - Created
  - Confirmed (once for every owner that confirmed)
  - Cancelled (No address connected here)

##### Tx not executed, but there is **no** other executed transaction with the same or higher nonce.

- That means the tx is `Waiting for confirmations`, `Waiting for execution` or `Pending`.

- Confirmations list includes the following for `Waiting for confirmations`:
  - Created 
  - Confirmed (once for every owner that confirmed)
  - Greyed out empty `execute` row

- Confirmations list includes the following for `Waiting for execution`:
  - Created 
  - Confirmed (once for every owner that confirmed)
  - Green empty `execute` row

- Confirmations list includes the following for `Pending`:
  - `Pending` is local to a device, i.e. only displayed when a txs was submitted (executed) from a device. Since we don't have this on mobile yet, **we don't need that state**.

# Updates
- (18.06.2020) Dima: removed screenshots as they were outdated

**Comment by liliya-soroka** [comment]
Found issues: 
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/304

verified app version 0.5.0 (62)
