### ISSUE TITLE
[iOS] Transaction details: header view

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-ios#188]
The header view of the transaction details

### Header UI Map
![TxDetailsHeaderUIMap.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c88dd473-7b04-40b4-98f3-956caeabad59)

#### Incoming ETH or ERC20
- [x] sender address
- [x] token logo and token amount

#### Outgoing ETH or ERC20
- [x] token logo and amount
- [x] recipient address
- [x] **NOTE**: if the transaction is failed, then token amount text color differs

#### Custom outgoing transaction
- [x] Amount of ETH
- [x] byte count
- [x] recipient address

#### addOwnerWithThreshold
- [x] address of added owner
- [x] updated threshold

#### removeOwners
- [x] address of removed owner
- [x] updated threshold

#### swapOwners
- [x] address of old owner to be removed
- [x] address of new owner to replace the old

#### changeMasterCopy
- display similar to the master copy in the Safe settings
  - [x] contract version (if master copy address is known - the version, otherwise - "Unknown")
  - [x] address of the master copy, truncated in the middle

#### Custom incoming transaction (ETH + data)
- [x] amount of ETH
- [x] byte count
- [x] sender address

#### setFallbackHandler
- Similar to the fallback handler in the advanced Safe settings
  - [x] Fallback handler title ("DefaultFallbackHandler" if known, otherwise "Unknown"
  - [x] address of the fallback handler

#### changeThreshold
- [x] new threshold

#### enableModule
- [x] module address

#### disableModule
- [x] module address

### ENS domain transfer
- [ ]  ENS name to be transferred
- [ ] sender/recipient depending if it is incoming/outgoing transfer

### ERC721 transfer
- [ ] NFT token address/ NFT contract name
- [ ] NFT token logo (optional)
- [ ] NFT name/description (truncated)
- [ ] sender/recipient depending if it is incoming/outgoing transfer

### Screenshots:
[https://zpl.io/2GJA7RJ](url)
[https://zpl.io/aBJKmGm](url)
[https://zpl.io/29xK4Ep](url)
[https://zpl.io/aBJKmGm](url)
[https://zpl.io/bWzjK01](url)
[https://zpl.io/VYgpw7k](url)

# What to test

Please test all of the variations with completed check marks. The ENS domain and ERC721 transfer are not implemented due to missing data. To be implemented in a separate issue.

**Comment by liliya-soroka** [comment]
1. Found issues in transaction header
 https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/305
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/280

2. ENS domain transfer and ERC721 transfer are not implemented @MouazAlzahabi and @DmitryBespalov - will you have separate tasks for ENS and ERC 721 or this one should be reopened?

verified: 0.5.0 (62)

**Comment by liliya-soroka** [comment]
Verified
app version 0.5.0 (65)
ENS and ERC721 are moved to the next sprint - the new issues will be created
