### ISSUE TITLE
ENS Reverse lookup not working

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios#193]
- This Safe has reverse ENS configured to `tttk.eth`:  `0xaE3c91c89153DEaC332Ab7BBd167164978638c30`
   - cf. https://rinkeby.etherscan.io/enslookup
- When I go to app settings, I see "reverse record not set" but I expect it to be set.

<img src="https://user-images.githubusercontent.com/1380529/83003393-8afc5380-a00e-11ea-88d1-6e6fbc3c257e.PNG" width="200" />

**Comment by tschubotz** [comment]
I just realized maybe I configured something wrong. Have to check.

**Comment by DmitryBespalov** [comment]
issue does not exist
