### ISSUE TITLE
Adjust the CI to publish the versions of the app

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#216]
- Create new staging mainnet scheme
- Change the build script to upload the staging 
- Change the app icons
- See if we can remove development (do we need them?)

### QA
- Please check that you have access to both the "Staging Rinkeby" and "Staging Mainnet" yellow apps via TestFlight

**Comment by liliya-soroka** [comment]
confirmed. There are two yellow appear in test flight : Rinkeby and Mainnet
