### ISSUE TITLE
Transaction List remaining (networking & data)

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#220]
Backend dependency:
- Queued transactions
- dataDecoding handling (recursive value types) not to break the app]

**Comment by DmitryBespalov** [comment]
Do we need the recursion? Can we just live with a stringified arrays, in all cases.

**Comment by DmitryBespalov** [comment]
https://github.com/gnosis/safe-transaction-service/issues/105

**Comment by tschubotz** [comment]
Sprint planning discussion: Since we don't need it anywhere in the UI, yet, we just ignore (i.e. don't parse) if it's not a string.
