### ISSUE TITLE
[IOS]Load Safe Multisig page: "Back" is missed

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-ios#222]
1. Click Load Safe Multisig or Add Safe 
2. Load Safe Multisig page is opened 

Current result: There is no " Back" near the < icon
Expected result:  
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b90b603b-9ca2-4a42-8a4f-fafa4607b8e6)
design : https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d58beea02bb4e3eb257

Devise: Iphone X
OS : 13.4.1
App version : yellow 0.4.0 (30)

**Comment by DmitryBespalov** [comment]
This is not feasible technically in the current SDK version. I know it is such a minor thing, but we have to wait for the update of the SDK later in the end of June to double-check this.

**Comment by tschubotz** [comment]
> This is not feasible technically in the current SDK version. I know it is such a minor thing, but we have to wait for the update of the SDK later in the end of June to double-check this.

Then let's check later.
But if iOS specifically recommends to not write "Back", then that's perhaps something we should consider for our designs as well @posthnikova

**Comment by posthnikova** [comment]
I'm fine with not having 'Back' text

**Comment by liliya-soroka** [comment]
Verified and closed as won't fix
