### ISSUE TITLE
[IOS]Enter ENS name: Wrong error message is no internet connection during ENS name searching

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-ios#223]
Steps to reproduce:
1. Open Add safe
2. Select Enter ENS name for entering safe address
3. Turn internet connection off
4. Start to type ENS name

Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3db5c645-1d0a-42d4-b027-400496daeb99)

Expected result: No internet connection notification should be shown instead of red error under the field
Design example: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ebbb3f7e3a0bc76f776d647

Devide: Iphone X
OS : 13.4.1
App version 0.4.0 (3)

**Comment by DmitryBespalov** [comment]
not implemented yet

**Comment by DmitryBespalov** [comment]
> Ideally, this should be a "snackbar" message about no internet above the keyboard.

**Comment by liliya-soroka** [comment]
Verified - red error under the field appears. 
app version 0.7.0 (108)
