### ISSUE TITLE
[IOS] Address format validation should be done on QR scanning page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-ios#224]
**Steps to reproduce:**
1. Open Load Safe multisig page to add new safe
2. Select "Scan QR code"
3. Scan QR code that doesn't contain ethereum address ( it may contain any URL or text)

**Current result**
QR scanning page is closed and the scanned text/url appears in the Enter safe address field  with the error message under it

**Expected result**
Ethereum address format validation should be done on the QR scanning page according to design - https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5eb03db89d4ade18f6f9dcd7

**Comment by DmitryBespalov** [comment]
@Tobias @posthnikova  I'd ask to keep the current implementation as is, as we check not only the address, but whether it is a safe, etc.

**Comment by posthnikova** [comment]
@DmitryBespalov I would still prefer checking to be done on the Camera screen. Putting wrong text into the address field is weird behaviour.

**Comment by DmitryBespalov** [comment]
Clear!

**Comment by liliya-soroka** [comment]
verified
app version 0.5.0 (62)
