### ISSUE TITLE
[IOS]The error is displayed on transaction list for new created safe 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-ios#228]
**Description** 
The red error is displayed on tx list page instead of Safe created tx for the just created safe

**Steps to reproduce**
1. Create new safe in web app
2. Load created safe in mobile app
3.Open transactions list

**Screenshot**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b77a9953-5201-4768-b22e-6177a317d5c4)

Device/OS : Iphone X /13.4.1
App version: yellow 0.4.0 (38)

**Comment by DmitryBespalov** [comment]
I think this is a backend issue, I created a bug ticket there:

https://github.com/gnosis/safe-transaction-service/issues/111

**Comment by liliya-soroka** [comment]
verified
app version 0.5.0 (62)
