### ISSUE TITLE
[iOS] WalletConnect doesn't work in Beta app

### ISSUE THREAD

**Issue by aquiladev** [gnosis/safe-ios#232]
**Bug description**
When I tried to connect to different DApps I had different errors. In some cases, the connection appeared in a list of connections in some cases not. Disconnect does not help.

**Steps To Reproduce**
1. create Safe for the first time
2. open the Safe
3. press WalletConnect button
4. scan QR code
5. nothing happened on the App side anymore, I see an error on a DApp side (address not detected)

**Device & App version**
 - Device/OS: iPhone6s/iOS13.4.1
 - App version: 1.13.2 (1) Pre-Production Rinkeby

**Comment by DmitryBespalov** [comment]
Hi, thanks for opening the issue. 😃  I'll check it. For information, the current app (incl. beta) is unlikely to get any updates, as we're working on a new one, and WalletConnect in a new mobile app is also not on the roadmap for the coming month or two
