### ISSUE TITLE
Restrict adding safe to the master copy >= 1.0.0

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#233]
# How to test
- Try adding a safe that has master copy other than in the list:
  - 0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F
  - 0xaE32496491b53841efb51829d6f886387708F99B
  - 0xb6029EA3B2c51D09a50B53CA8012FeEB05bDa35A

For example, safes with the following master copies should not be addable:
 - 0x8942595A2dC5181Df0465AF0D7be08c8f23C93af

Example of a safe that has unknown master copy:
 - 0xb19BDaFf408bB502Ae348aF731C3812670667224

For such safes, when the safe address is entered, the app will show error that the safe master copy is not supported.

**Comment by liliya-soroka** [comment]
Verified.
app version 0.5.0 (65)
