### ISSUE TITLE
[iOS] Tx amount =0 on UI if the tx amount <=0.000009 ( 6 number after decimal symbol)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-ios#248]
**Bug description**
Tx amount =0 on UI if the tx amount <=0.000009 ( 6 number after decimal symbol)
The safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( ens liltestsafe.eth) 
Transactions: 
Nonce: 31
Nonce: 28

**Steps To Reproduce**
1. Load 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( ens name liltestsafe.eth)
2. Create outgoing  transaction with amount 0.0000005 or less
3. Confirm and execute transaction 
4. Open transaction details in the mobile app

**Expected Result**
??? The web app displays < 0.001 ETH . Need to discuss how to display....
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/792c7a85-e2fa-443c-9929-92eceaffcebf)
**Device & App version**
 - Device/OS: iPhone X/13.15.1
 - App version: 0.4.0 (46)

**Additional info**
(Optional)

**Comment by tschubotz** [comment]
I would not change the requirements but rather change this later with this ticket: gnosis/safe#332

**Comment by MouazAlzahabi** [comment]
@tschubotz It seems that the ticket link is worng

**Comment by tschubotz** [comment]
@MouazAlzahabi fixed, thanks :)

**Comment by liliya-soroka** [comment]
The Epic was created.
The issue can be closed
