### ISSUE TITLE
For displaying the ENS and ERC721 we need additional data from the backend or blockchain

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#253]
### ERC721
For the transaction transfering ERC721 tokens, we need several pieces of data:
- token uri
- token name
- token id (already exists in the response)
- token description
- token contract address (already exists in the response)
Where and how do we get others?

The token name is also needed for the transaction list.
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/edcb9fe0-70c2-41bb-9e3b-c740cfeab0fb" width=300/>

### ENS
For ENS transfers (also ERC721 tokens but the ENS contracts don't provide the info of ERC721), we need to resolve the ENS name from the token id to figure out which name was transferred. Is that possible to do, at all? What if there is no reverse resolver? Does the OpenSea have this information?

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/16db4ff2-a0fb-4638-92f9-14f4e48e715c" width=300/>

**Comment by sche** [comment]
TODO: update product ticket after requirements refinement

**Comment by DmitryBespalov** [comment]
closing because of duplicate
