### ISSUE TITLE
[iOS] No Eth icon in transaction details

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios#275]
**Bug description**
No Eth icon in transaction details

**Steps To Reproduce**
Open a tx with outgoing/incoming Eth

**Expected Result**
Eth icon in header view

**Screenshots**
![IMG_804731B231AD-1](https://user-images.githubusercontent.com/2284385/85122629-299f5d00-b227-11ea-9efb-1a2080561bba.jpeg)

**Comment by liliya-soroka** [comment]
verified
app version 0.5.0 (62)
