### ISSUE TITLE
[iOS] Tooltip

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#31]
Tooltip as a feedback on copying anything in the app (UI design from the safe app)

# NOTE
During implementation, it turned out that the tooltip is interfering with the system behavior, and it is not showing in some situations (when address is in the list, like in Safe Settings). Unfortunately, it is not fixable at the moment.

Per discussion with Sasha, we decided to show the snackbar notification instead.

# How to test

Tap on an address in Settings and in other places, it should show the "Copied to clipboard" snackbar message.

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (99)
