### ISSUE TITLE
MultisigWalletDomainModel.CommunicationDomainService.CommunicationError

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios#40]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/bdfec034858cd3eb4733566f79c630b2?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/bdfec034858cd3eb4733566f79c630b2?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
won't fix
