### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#47]
Make a consistent error handling solution for handling networking errors, server response errors, validation errors, database errors, and third-party library errors.

This is about UI and about error handling in the code.

**Comment by sche** [comment]
How to test crashlytics integration:

Precondition: upload dSym files for the release

- Check that Debug crash is reported

- Use proxy to trigger a not known error (e.g. 422 HTTP error with data={'code': 1000})
=> a custom error "Unrecognised error code: 1000" should be logged to the crashlytics

**Comment by liliya-soroka** [comment]
Verified
one minor issues with UI error
app version 0.7.0 (93)
