### ISSUE TITLE
Splash screen has wrong font

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#56]
The splash screen is not using the Averta font. The issue was that the custom fonts are not supported in the launch screens, so we need to use an image instead. The image is ready to use in Zeplin.

Here's the current state:
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/1b6e14fc-978e-458e-8b59-a61bb4ec19a4" width=600px/>

**Comment by sche** [comment]
so we will need to localize images as well, right?

**Comment by DmitryBespalov** [comment]
I think so, localize the launch screens 🗺️
