### ISSUE TITLE
Empty balances screen visual differences from the UI designs

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#57]
- [x] Height of the navbar is too small
- [x] Somehow the font of the label in designs is different from the standard font of the iOS
- [x] The load button width is too small
- [x] The "Balances" tab should be named "Assets"

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/305bbc41-6f2e-40c2-ac8b-e7484278cf4f" width=600px/>

**Comment by sche** [comment]
- Extend tappable area for both elements (safe details / safe selection)

**Comment by DmitryBespalov** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/
> For SF, use Text for text that's smaller than 20 points; use Display for text that's 20 points or larger.

The designs are using SF Pro Text, which is not what the system uses. We need to update designs.
