### ISSUE TITLE
ENS name entry visual differences with the UI design

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#64]
- [x] The ENS name is auto-capitalized, this should not be the case. Also, the grammar correction should be disabled.
- [x] Add "." to the keyboard by default (I think there should be a separate keyboard for that)
- [x] The text field border and icon are not what the UI specifies
- [x] The check mark icon is in the wrong place (should be near the "Address found" text)
- [x] The address text is not bold as it should be in the design.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/15cdfa7e-1d04-47a0-a23e-36672e112472" width=600px/>

**Comment by sche** [comment]
- Add "." to the keyboard by default (I think there should be a separate keyboard for that)
