### ISSUE TITLE
Safe Settings visual differences with UI designs

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#68]
- [x] Height of normal cells differs
- [x] Height of the cells with addresses differs
- [x] The address text is not bold
- [x] The "arrow" button is bold

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/1e28eab2-fc20-48ee-bac2-2414122987c6" width=600px/>

**Comment by sche** [comment]
- "share icon" should not be bold
- Background color behind the list should be like section header color
- Pull to refresh is not implemented
- No background --> foreground refresh is implemented
- "Not Set" in ENS name. Should be "Not set"
