### ISSUE TITLE
Safe Settings does not display the upgrade status

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#69]
The contract version cell must display either that the contract is up to date, or upgrade available, or, if the master copy is not known, display "Unknown".

Here is the list of contract versions and master copy addresses:
      - master_copy: "0xAC6072986E985aaBE7804695EC2d8970Cf7541A2" version: "0.0.2"
      - master_copy: "0x8942595A2dC5181Df0465AF0D7be08c8f23C93af" version: "0.1.0"
      - master_copy: "0xb6029EA3B2c51D09a50B53CA8012FeEB05bDa35A" version: "1.0.0"
      - master_copy: "0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F" version: "1.1.1"

If the master copy of the safe is not one of the addresses above, then we display "Unknown" as the contract version.
Otherwise, if the master copy is the latest master copy, we display the "Up to date" UI
Otherwise we display "Upgrade available".

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/0225a7cf-bb50-441c-b5fc-207b2ad7af14" width=600px/>

**Comment by sche** [comment]
+ "share icon" should not be bold

**Comment by DmitryBespalov** [comment]
>     * "share icon" should not be bold

The share icon is in a different ticket
