### ISSUE TITLE
Advanced Safe Settings content

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#70]
- [x] We need not to show the master copy address, because we already show it in the main screen together with the contract version
- [x] The fallback handler should have a human-readable text. If the handler is our default address (right now it is 0xd5D82B6aDDc9027B22dCA772Aa68D5d74cdBdF44), then we display "DefaultFallbackHandler". If it is a zero address, we should display text "Not set" and do not display the address. In other cases, we should display "Unknown".
- [x] The screen should show the addresses truncated as in the designs

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e8015487-7644-4fef-ac48-be3ef66cfe55" width=600px/>

**Comment by sche** [comment]
I would add here the "share icon" should be not bold.

**Comment by DmitryBespalov** [comment]
> I would add here the "share icon" should be not bold.

This is mentioned in a different ticket, I think
