### ISSUE TITLE
ه

### ISSUE THREAD

**Issue by nasser666679** [gnosis/safe-ios#778]
After our app has been running in the background for a long time, the normal tabbar icon becomes a color block. Not necessarily, but occasionally。Another widget turned into a pink block.

![image](https://user-images.githubusercontent.com/28725950/101761236-da235500-3b16-11eb-8504-23d3418a40b9.png)

![image](https://user-images.githubusercontent.com/28725950/101761462-22427780-3b17-11eb-81a2-f740a646c6bb.png)

__Originally posted by @XGNoCopy in https://github.com/flutter/flutter/issues/72058__

**Comment by DmitryBespalov** [comment]
Hi, this must be a mistake - please open the issue in flutter
