### ISSUE TITLE
[iOS] View ETH and ERC20 token balance

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#88]
- User can see their ETH balance, ETH is always on top
- User can see the balance of all ERC20 tokens with balance > 0, tokens are ordered by their names, ascending
- User sees fiat value in USD per asset
- On appear or coming to foreground, the screen should refresh if it is shown to the user (whenever the screen is destroyed by the OS).
- Pull to refresh will reload the balances manually

### API Services

- To get the balances, use the transaction service:
  - https://safe-transaction.gnosis.io/
  - GET /safes/{address}/balances/usd/
  - [x] The balances are not paginated
  - Returns both the token balance and the balance in USD
  - the "null" token is "ETH" token.
  - The endpoint returns the token information (name, decimals). 
  - The logo is to be added, but for now you can take it by using the URL as a template from the relay service.
    - https://safe-relay.gnosis.io/
    - endpoint GET /v1/tokens/

## Depends on 
https://github.com/gnosis/safe-transaction-service/issues/91
https://github.com/gnosis/safe-transaction-service/issues/86

<img width="487" alt="Screenshot 2020-05-11 at 19 09 31" src="https://user-images.githubusercontent.com/284056/81591388-e2ae8400-93ab-11ea-8dd0-1028220ac484.png">

**Comment by DmitryBespalov** [comment]
1. It is better for us if the relay service would provide the token information embedded in the balance response (with the token name, decimals, description and image URL as a token object)
2. In the same way, is it feasible to return the values not in USD but in other fiat if we request it with the "symbol" parameter?

**Comment by DmitryBespalov** [comment]
3. In the user research, people were interested in seeing their total value of all of their assets, do we want to add it now or at some point later?

**Comment by DmitryBespalov** [comment]
4. Pagination

**Comment by sche** [comment]
So we will not use conversion rates, right?

**Comment by DmitryBespalov** [comment]
> So we will not use conversion rates, right?
yes, that's right
