### ISSUE TITLE
[iOS] Fiat currencies management

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-ios#93]
- [ ] Create currency model
- [ ] Load currencies
- [ ] display fiat currencies
- [ ] Store selected currency 

https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ea9664cfda2592706e3f64b

<img width="487" alt="Screenshot 2020-05-11 at 21 54 26" src="https://user-images.githubusercontent.com/284056/81605600-3b3c4c00-93c1-11ea-9fa2-aea7bd7d6096.png">

**Comment by DmitryBespalov** [comment]
I think loading currencies would not be the case here, I would have for the beginning a static list hard-coded in the app (or supplied from the configuration file)

**Comment by DmitryBespalov** [comment]
the epic ticket for fiat currencies is scoped for phase 2, so I would postpone this issue for much later point.

**Comment by DmitryBespalov** [comment]
@tschubotz should we keep that or close it?

**Comment by tschubotz** [comment]
let's close it and rather reopen when/if we touch the related epic.
