### ISSUE TITLE
[iOS] Tracking

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios#95]
[+] Handling firebase configuration files (use encrypted files)
[+] Handling firebase configurations for different envs
[+] Add firebase to the project
[+] Add pod file
[+] Copy Tracker files from the old project (console/firebase tracking), or use some 3rd party lib 
[+] Setup user properties: - num_safes
[+] Disable personalized tracking
[+] Check on automatic/manual screen tracking (experiment with firebase debug view)
[+] Align with Android & product on tracking events names for screens (Should we be aligned with Android?)

# What to test
The tracking events are listed here: https://docs.google.com/spreadsheets/d/1KVaeOZ21aaNgR2jc5JM69gj0NWaOdOhlyhYXUMzh1l4/edit#gid=783259250

Only screen events are implemented. 

When the screen is shown the first time, or after it was covered by another screen, the event should be fired.

**Comment by liliya-soroka** [comment]
No time to test it during sprint 5 .
The task is closed as done but it will be tested completely at the beginning of the sprint 6 
assigned to Liliya Soroka
