### ISSUE TITLE
Switch Safe ordering

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#97]
Safes are sorted in the order in which they were added. 

Active Safe is at the top. 

When you select another Safe in the list, the order does not change right away, but only when you open the switch safe screen again - then this selected Safe is at the top. 

Newly added Safe becomes active Safe, and hence will be at the top.

**Comment by sche** [comment]
I discussed it with @posthnikova 
Because of the resolution not to implement the bottom sheet [here](https://github.com/gnosis/safe-ios/issues/67) this issue also does not make much sense.
Current resolution: we will not implement it.
I will add a label and a dependency

**Comment by tschubotz** [comment]
I think also it is fine not to implement this. Added a note in gnosis/safe#285

**Comment by sche** [comment]
@tschubotz tech preference would be to keep it as it is on both clients (Android and iOS will be a bit different). Is it okay for you?
@posthnikova confirms that she is ok with it

**Comment by tschubotz** [comment]
yep, okay for me :)
