### ISSUE TITLE
QR code scan does not work on Etherscan dark mode

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios#99]
I'm on the most recent Testflight version of the new app.

On desktop:
- Go to https://rinkeby.etherscan.io/address/0x9D2407C6b6c1C307AB54Adb01627Ba0845e3Cddf
- Switch to dark mode via the 🌚 on the bottom right corner.
- Display QR code via the button next to the address

On mobile:
- Add new Safe
- Scan QR code
-> Nothing happens

Expected result: scanning works.

With "day" mode, everything works fine with this address.

Here's the QR code image from Etherscan for easy access:
![image](https://user-images.githubusercontent.com/1380529/81713465-338aaf00-9476-11ea-9f45-b33b49c4d3bf.png)

**Comment by MouazAlzahabi** [comment]
@tschubotz 
I couldn't even scan this code in different QR scanning apps, also we use the system scanner so no configuration to improve sensitivity, so it seems to be problem with the image itself.

Can you please confirm.

**Comment by tschubotz** [comment]
Hmm. I was under the impression that it worked for me in other apps. But your are right, it doesn't currently. Not sure what I was thinking there. Thanks for checking.
